INSERT INTO unit8schema.author (id, name)
    SELECT nextval('unit8schema.author_seq'), 'Иммануил Кант'
UNION ALL SELECT nextval('unit8schema.author_seq'), 'Терри Пратчетт'
UNION ALL SELECT nextval('unit8schema.author_seq'), 'Ричард Докинз'
;

INSERT INTO unit8schema.book (id, name, author_id, current_reader_id)
    SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 1. — М., 1963, 543 с (Философское наследие, Т. 4)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 2. — М., 1964, 510 с (Философское наследие, Т. 5)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 3. — М., 1964, 799 с (Философское наследие, Т. 6)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 4, часть 1. — М., 1965, 544 с (Философское наследие, Т. 14)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 4, часть 2. — М., 1965, 478 с (Философское наследие, Т. 15)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 5. — М., 1966, 564 с (Философское наследие, Т. 16)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Сочинения в шести томах. Том 6. — М., 1966, 743 с (Философское наследие, Т. 17)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Трактаты и письма. — М.: «Наука», 1980, 710 с. (Памятники философской мысли)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Критика чистого разума. — М., 1994, 574 с (Философское наследие, Т. 118)', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Собрание сочинений в 8 томах. — Издательство: ЧОРО, 1994 г. — ISBN 5-8497-0001-3, ISBN 5-8497-0002-1, ISBN 5-8497-0003-X, ISBN 5-8497-0004-8, ISBN 5-8497-0005-6, ISBN 5-8497-0006-4, ISBN 5-8497-0007-2, ISBN 5-8497-0008-0.', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Лекции по этике. — М.: Республика, 2000. — 431 с.', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Критика чистого разума / Пер. с нем. Н. Лосского сверен и отредактирован Ц. Г. Арзаканяном и М. И. Иткиным; Примеч. Ц. Г. Арзаканяна. — М.: Эксмо, 2007. — 736 с. — ISBN 5-699-14702-0', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Критика чистого разума / (Пер. с нем.; предисл. И. Евлампиева). — М.: Эксмо; СПб.:Мидгард, 2007. — 1120 с. — (Гиганты мысли) — ISBN 5-91016-017-4', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Лекции о философском учении о религии / И. Кант; пер. с нем. Л. Э. Крыштоп. — М.: Канон+, 2016. — 384 с. — ISBN 978-5-88373-004-6', (SELECT id FROM unit8schema.author WHERE name = 'Иммануил Кант'), CAST(null AS INTEGER)

UNION ALL SELECT nextval('unit8schema.book_seq'), 'Цвет волшебства', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Безумная звезда', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Творцы заклинаний', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Мор, ученик Смерти', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Посох и шляпа', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Вещие сестрички', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Пирамиды', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Стража! Стража!', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Эрик, а также Ночная стража, ведьмы и Коэн-Варвар', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Движущиеся картинки', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Мрачный Жнец', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Ведьмы за границей', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Мелкие боги', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Дамы и Господа', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'К оружию! К оружию!', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Роковая музыка', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Интересные времена', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Маскарад', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Ноги из глины', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Санта-Хрякус', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Патриот', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Последний континент', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Carpe Jugulum. Хватай за горло', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Пятый элефант', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Правда', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Вор времени', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Последний герой', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Удивительный Морис и его учёные грызуны', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Ночная стража', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Маленький свободный народ', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Пехотная баллада', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Шляпа, полная неба', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Держи марку!', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Шмяк!', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Зимних дел мастер', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Делай деньги', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Незримые академики', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Я надену полночь', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Дело табак', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Raising Steam', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Корона пастуха', (SELECT id FROM unit8schema.author WHERE name = 'Терри Пратчетт'), CAST(null AS INTEGER)

UNION ALL SELECT nextval('unit8schema.book_seq'), 'Эгоистичный ген', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Расширенный фенотип', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Слепой часовщик', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Река, текущая из рая', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Поднимаясь на пик невероятного', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Расплетая радугу', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Капеллан дьявола; сборник эссе и статей', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Рассказ предка', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Бог как иллюзия', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Ричард Докинз. Самое грандиозное шоу на Земле. Доказательства эволюции', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'Магия реальности: откуда мы знаем что является правдой', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)
UNION ALL SELECT nextval('unit8schema.book_seq'), 'An Appetite for Wonder: The Making of a Scientist', (SELECT id FROM unit8schema.author WHERE name = 'Ричард Докинз'), CAST(null AS INTEGER)

